# -*- coding: utf-8 -*

import os

DEFAULT_F_MIN = 20
DEFAULT_F_MAX = 20000
DEFAULT_STEP = 1.01

DEFAULT_MAX_GAIN = 6.0
DEFAULT_TREBLE_F_LOWER = 6000.0
DEFAULT_TREBLE_F_UPPER = 8000.0
DEFAULT_TREBLE_MAX_GAIN = 0.0
DEFAULT_TREBLE_GAIN_K = 1.0

DEFAULT_SMOOTHING_WINDOW_SIZE = 1 / 6
DEFAULT_SMOOTHING_ITERATIONS = 1
DEFAULT_TREBLE_SMOOTHING_F_LOWER = 100.0
DEFAULT_TREBLE_SMOOTHING_F_UPPER = 10000.0
DEFAULT_TREBLE_SMOOTHING_WINDOW_SIZE = 1 / 3
DEFAULT_TREBLE_SMOOTHING_ITERATIONS = 1
DEFAULT_TILT = 0.0
DEFAULT_FS = 44100
DEFAULT_BIT_DEPTH = 16
DEFAULT_PHASE = 'minimum'
DEFAULT_F_RES = 10
DEFAULT_BASS_BOOST_GAIN = 0
DEFAULT_BASS_BOOST_FC = 100
DEFAULT_BASS_BOOST_Q = 0.65

DEFAULT_GRAPHIC_EQ_STEP = 1.1

ROOT_DIR = os.path.abspath(os.path.dirname(os.path.abspath(__file__)))
MOD_REGEX = r' \((sample|serial number) [a-zA-Z0-9\-]+\)$'
